=== CroatiaControlLtd/asterix/install/config/asterix.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--

	DTD for Asterix format
	
	Author:   dsalantic
	Created:  24.12.2008.
				
-->

<!ELEMENT Category (DataItem*,UAP*)>
	<!ATTLIST Category id CDATA #REQUIRED>
	<!ATTLIST Category name CDATA #REQUIRED>
	<!ATTLIST Category ver CDATA #REQUIRED>

	<!ELEMENT Bits (BitsShortName?,BitsName?,(BitsConst|BitsValue*|BitsUnit|BitsPresence),XIDEF?)>
		<!ATTLIST Bits bit CDATA "0">
		<!ATTLIST Bits from CDATA "0">
		<!ATTLIST Bits to CDATA "0">
		<!ATTLIST Bits encode (signed|6bitschar|octal|unsigned|ascii) "unsigned">
		<!ATTLIST Bits fx CDATA "0">
		<!ATTLIST Bits rep CDATA "0">
		<!ELEMENT BitsShortName (#PCDATA)>
		<!ELEMENT BitsName (#PCDATA)>
		<!ELEMENT XIDEF (#PCDATA)>
		<!ELEMENT BitsValue (#PCDATA)>
			<!ATTLIST BitsValue val CDATA "0" >
			<!-- TODO <!ATTLIST BitsValue from CDATA "0" > -->
			<!-- TODO <!ATTLIST BitsValue to CDATA "0" > -->
		<!ELEMENT BitsConst (#PCDATA)>
		<!ELEMENT BitsPresence (#PCDATA)>
		<!ELEMENT BitsUnit (#PCDATA)>
			<!ATTLIST BitsUnit scale CDATA "1" >
			<!ATTLIST BitsUnit min CDATA "0" >
			<!ATTLIST BitsUnit max CDATA "0" >

	<!ELEMENT DataItem (DataItemName,DataItemDefinition,DataItemFormat,DataItemNote?)>
		<!ATTLIST DataItem id CDATA #REQUIRED>
		<!ATTLIST DataItem rule (mandatory|optional|unknown) "unknown">
		<!ELEMENT DataItemName (#PCDATA)>
		<!ELEMENT DataItemDefinition (#PCDATA)>
		<!ELEMENT DataItemNote (#PCDATA)>
		<!ELEMENT DataItemFormat (Fixed|Explicit|Repetitive|Variable|Compound)>
			<!ATTLIST DataItemFormat desc CDATA "" >

			<!-- Fixed length data fields -->
			<!ELEMENT Fixed (XIDEF?,Bits+)>
				<!ATTLIST Fixed length CDATA "1" >

			<!-- Explicit length data fields -->
			<!ELEMENT Explicit (Fixed+)>

			<!-- Repetitive length data fields -->
			<!ELEMENT Repetitive (Fixed+)>

			<!-- Variable (extended) length data fields -->
			<!ELEMENT Variable (Fixed+)>

			<!-- Compund data fields -->
			<!ELEMENT Compound (Variable,(Fixed|Explicit|Repetitive|Variable)*)>

	<!-- User Application Profile -->
	<!ELEMENT UAP (UAPItem*)>
	<!ATTLIST UAP use_if_bit_set CDATA "0">
	<!ATTLIST UAP use_if_byte_nr CDATA "0">
	<!ATTLIST UAP is_set_to CDATA "0">
	<!ELEMENT UAPItem (#PCDATA)>
	<!ATTLIST UAPItem bit CDATA #REQUIRED>
	<!ATTLIST UAPItem frn CDATA #REQUIRED>
	<!ATTLIST UAPItem fx CDATA "0">
	<!ATTLIST UAPItem len CDATA "-">

=== CroatiaControlLtd/asterix/install/config/asterix_bds.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Category SYSTEM "asterix.dtd">

<!--  

	Mode S BDS registers definition 
	
	Author:   dsalantic
	Created:  5.5.2016.
	

--> 

<Category id="BDS" name="BDS" ver="1.0">
	
	<DataItem id="40">
		<DataItemName>Selected vertical intention</DataItemName>
		<DataItemDefinition>Selected vertical intention</DataItemDefinition>
		<DataItemFormat desc="Seven-octets fixed length data item.">
			<Fixed length="7">
				<Bits bit="56">
					<BitsShortName>MCP_ALT_STATUS</BitsShortName>
					<BitsName>MCP Altitude Status</BitsName>
				</Bits>
				<Bits from="55" to="44" encode="unsigned">
					<BitsShortName>MCP_ALT</BitsShortName>
					<BitsName>MCP/FCU Selected Altitude</BitsName>
                    <BitsUnit scale="16">ft</BitsUnit>
				</Bits>
				<Bits bit="43">
					<BitsShortName>FMS_ALT_STATUS</BitsShortName>
					<BitsName>FMS Altitude Status</BitsName>
				</Bits>
				<Bits from="42" to="31" encode="unsigned">
					<BitsShortName>FMS_ALT</BitsShortName>
					<BitsName>FMS Selected Altitude</BitsName>
                    <BitsUnit scale="16">ft</BitsUnit>
				</Bits>
				<Bits bit="30">
					<BitsShortName>BP_STATUS</BitsShortName>
					<BitsName>Barometric Pressure Status</BitsName>
				</Bits>
				<Bits from="29" to="18" encode="unsigned">
					<BitsShortName>BP</BitsShortName>
					<BitsName>Barometric Pressure</BitsName>
                    <BitsUnit scale="0.1">mb</BitsUnit>
				</Bits>
				<Bits from="17" to="10">
					<BitsShortName>res</BitsShortName>
					<BitsName>Reserved</BitsName>
				</Bits>
				<Bits bit="9">
					<BitsShortName>MODE_STATUS</BitsShortName>
					<BitsName>Status of MCP/FCU Mode Bits</BitsName>
				</Bits>
                <Bits bit="8">
                    <BitsShortName>VNAV</BitsShortName>
					<BitsName>VNAV Mode</BitsName>
                    <BitsValue val="0">Not active</BitsValue>
                    <BitsValue val="1">Active</BitsValue>
                </Bits>
                <Bits bit="7">
                    <BitsShortName>ALTHOLD</BitsShortName>
					<BitsName>ALT HOLD Mode</BitsName>
                    <BitsValue val="0">Not active</BitsValue>
                    <BitsValue val="1">Active</BitsValue>
                </Bits>
                <Bits bit="6">
                    <BitsShortName>APPMODE</BitsShortName>
					<BitsName>APPROACH Mode</BitsName>
                    <BitsValue val="0">Not active</BitsValue>
                    <BitsValue val="1">Active</BitsValue>
                </Bits>
				<Bits from="5" to="4">
					<BitsShortName>res</BitsShortName>
					<BitsName>Reserved</BitsName>
				</Bits>
                <Bits bit="3">
                    <BitsShortName>TARGETALTSTAT</BitsShortName>
					<BitsName>Status of Target ALT source bits</BitsName>
                    <BitsValue val="0">No source information provided</BitsValue>
                    <BitsValue val="1">Source information deliberately provided</BitsValue>
                </Bits>
                <Bits from="2" to="1">
                    <BitsShortName>TARGETALTSRC</BitsShortName>
					<BitsName>Target ALT source</BitsName>
                    <BitsValue val="0">Unknown</BitsValue>
                    <BitsValue val="1">Aircraft Altitude</BitsValue>
                    <BitsValue val="0">FCU/MCP selected altitude</BitsValue>
                    <BitsValue val="1">FMS selected altitude</BitsValue>
                </Bits>
			</Fixed>
		</DataItemFormat>
	</DataItem>

	<DataItem id="50">
		<DataItemName>Track and turn report</DataItemName>
		<DataItemDefinition>Track and turn report</DataItemDefinition>
		<DataItemFormat desc="Seven-octets fixed length data item.">
			<Fixed length="7">
				<Bits bit="56">
					<BitsShortName>ROLL_STATUS</BitsShortName>
					<BitsName>Roll Angle Status</BitsName>
				</Bits>
				<Bits bit="55">
					<BitsShortName>ROLL_SIGN_DIR</BitsShortName>
					<BitsName>Roll Angle Direction</BitsName>
                    <BitsValue val="0">Right wing down</BitsValue>
                    <BitsValue val="1">Left wing down</BitsValue>
				</Bits>
				<Bits from="54" to="46" encode="signed">
					<BitsShortName>ROLL_ANGLE</BitsShortName>
					<BitsName>Roll angle</BitsName>
                    <BitsUnit scale="0.17578125">deg</BitsUnit>
				</Bits>
				<Bits bit="45">
					<BitsShortName>TRUE_TRACK_STATUS</BitsShortName>
					<BitsName>True Track Angle Status</BitsName>
				</Bits>
				<Bits bit="44">
					<BitsShortName>TRUE_TRACK_ANGLE_DIR</BitsShortName>
					<BitsName>True Track Angle Direction</BitsName>
                    <BitsValue val="0">East</BitsValue>
                    <BitsValue val="1">West</BitsValue>
				</Bits>
				<Bits from="43" to="34" encode="signed">
					<BitsShortName>TRU_TRACK_ANGLE</BitsShortName>
					<BitsName>True track angle</BitsName>
                    <BitsUnit scale="0.17578125">deg</BitsUnit>
				</Bits>
				<Bits bit="33">
					<BitsShortName>GS_STATUS</BitsShortName>
					<BitsName>Ground Speed Status</BitsName>
				</Bits>
				<Bits from="32" to="23" encode="unsigned">
					<BitsShortName>GS</BitsShortName>
					<BitsName>Ground Speed</BitsName>
                    <BitsUnit scale="2">kt</BitsUnit>
				</Bits>
				<Bits bit="22">
					<BitsShortName>TRACK_ANGLE_RATE_STATUS</BitsShortName>
					<BitsName>Track Angle Rate Status</BitsName>
				</Bits>
				<Bits bit="21">
					<BitsShortName>TRACK_ANGLE_RATE_SIGN</BitsShortName>
					<BitsName>Track Angle Rate Sign</BitsName>
                    <BitsValue val="0">Plus</BitsValue>
                    <BitsValue val="1">Minus</BitsValue>
				</Bits>
				<Bits from="20" to="12" encode="signed">
					<BitsShortName>TRACK_ANGLE_RATE</BitsShortName>
					<BitsName>Track angle rate</BitsName>
                    <BitsUnit scale="0.03125">deg/sec</BitsUnit>
				</Bits>
				<Bits bit="11">
					<BitsShortName>TAS_STATUS</BitsShortName>
					<BitsName>True Airspeed Status</BitsName>
				</Bits>
				<Bits from="10" to="1" encode="signed">
					<BitsShortName>TAS</BitsShortName>
					<BitsName>True Airspeed</BitsName>
                    <BitsUnit scale="2">kt</BitsUnit>
				</Bits>
			</Fixed>
		</DataItemFormat>
	</DataItem>

	<DataItem id="60">
		<DataItemName>Heading and Speed Report</DataItemName>
		<DataItemDefinition>Heading and Speed Report</DataItemDefinition>
		<DataItemFormat desc="Seven-octets fixed length data item.">
			<Fixed length="7">
				<Bits bit="56">
					<BitsShortName>HDG_STAT</BitsShortName>
					<BitsName>Heading Status</BitsName>
				</Bits>
				<Bits bit="55">
					<BitsShortName>HDG_DIR</BitsShortName>
					<BitsName>Head Direction</BitsName>
                    <BitsValue val="0">East</BitsValue>
                    <BitsValue val="1">West</BitsValue>
				</Bits>
				<Bits from="54" to="45" encode="unsigned">
					<BitsShortName>HDG</BitsShortName>
					<BitsName>Magnetic Heading</BitsName>
                    <BitsUnit scale="0.17578125">deg</BitsUnit>
				</Bits>
				<Bits bit="44">
					<BitsShortName>IAS_STAT</BitsShortName>
					<BitsName>Indicated Airspeed Status</BitsName>
				</Bits>
				<Bits from="43" to="34">
					<BitsShortName>IAS</BitsShortName>
					<BitsName>Indicated Airspeed</BitsName>
                    <BitsUnit scale="1">kt</BitsUnit>
				</Bits>
				<Bits bit="33">
					<BitsShortName>MACH_STAT</BitsShortName>
					<BitsName>Mach Speed Status</BitsName>
				</Bits>
				<Bits from="32" to="23">
					<BitsShortName>MACH</BitsShortName>
					<BitsName>Mach Speed</BitsName>
                    <BitsUnit scale=".004">MACH</BitsUnit>
				</Bits>
				<Bits bit="22">
					<BitsShortName>BAR_STAT</BitsShortName>
					<BitsName>Barometric Altitude Rate Status</BitsName>
				</Bits>
				<Bits bit="21">
					<BitsShortName>BAR_DIR</BitsShortName>
					<BitsName>Barometric Altitude Rate Direction</BitsName>
                    <BitsValue val="0">Above</BitsValue>
                    <BitsValue val="1">Below</BitsValue>
				</Bits>
				<Bits from="20" to="12" encode="unsigned">
					<BitsShortName>BAR</BitsShortName>
					<BitsName>Barometric Altitude Rate</BitsName>
                    <BitsUnit scale="32">ft/min</BitsUnit>
				</Bits>
				<Bits bit="11">
					<BitsShortName>IVV_STAT</BitsShortName>
					<BitsName>Inertial Vertical Velocity Status</BitsName>
				</Bits>
				<Bits from="10" to="1" encode="unsigned">
					<BitsShortName>IVV</BitsShortName>
					<BitsName>Inertial Vertical Velocity </BitsName>
                    <BitsUnit scale="32">ft/min</BitsUnit>
				</Bits>
			</Fixed>
		</DataItemFormat>
	</DataItem>

	<DataItem id="00"> <!-- This must be last item  -->
		<DataItemName>BDS register</DataItemName>
		<DataItemDefinition>BDS register</DataItemDefinition>
		<DataItemFormat desc="Seven-octets fixed length data item.">
			<Fixed length="7">
				<Bits from="56" to="1" encode="hex">
					<BitsShortName>BDS</BitsShortName>
					<BitsName>BDS value</BitsName>
				</Bits>
			</Fixed>
		</DataItemFormat>
	</DataItem>
    
 </Category>

=== CroatiaControlLtd/asterix/install/config/asterix_cat065_1_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Category SYSTEM "asterix.dtd">

<!--  

	Asterix Category 65 v1.3 definition 
	
	Author:   dmarkus
	Created:  29.10.2012.
	Modified:  28.4.2014. (dsalantic) Special characters removed from BitsShortName, some BitsShortName renamed, tabs aligned

--> 

<Category id="65" name="SDPS Service Status Messages" ver="1.3">

	<DataItem id="000">
		<DataItemName>Message Type</DataItemName>
		<DataItemDefinition>This Data Item allows for a more convenient handling of the messages at the receiver side by further defining the type of transaction.</DataItemDefinition>
		<DataItemFormat desc="One-octet fixed length Data Item.">
			<Fixed length="1">
				<Bits from="8" to="1">
					<BitsShortName>Typ</BitsShortName>
					<BitsName>Message Type</BitsName>
                    				<BitsValue val="1">SDPS Status</BitsValue>
                    				<BitsValue val="2">End of Batch</BitsValue>
                    				<BitsValue val="3">Service Status Report</BitsValue>
				</Bits>
			</Fixed>
		</DataItemFormat>
	</DataItem>
	
	<DataItem id="010">
		<DataItemName>Data Source Identifier</DataItemName>
		<DataItemDefinition>Identification of the SDPS sending the data.</DataItemDefinition>
		<DataItemFormat desc="Two-byte fixed length data item.">
			<Fixed length="2">
				<Bits from="16" to="9">
					<BitsShortName>SAC</BitsShortName>
					<BitsName>Source Area Code</BitsName>
				</Bits>
				<Bits from="8" to="1">
					<BitsShortName>SIC</BitsShortName>
					<BitsName>Source Identification Code</BitsName>
				</Bits>
			</Fixed>
		</DataItemFormat>
	</DataItem>
    
	<DataItem id="015">
		<DataItemName>Service Identification</DataItemName>
		<DataItemDefinition>Identification of the service provided to one or more users.</DataItemDefinition>
        	<DataItemFormat desc="One-Octet fixed length data item.">
		            <Fixed length="1">
		                <Bits from="8" to="1">
					<BitsShortName>SID</BitsShortName>
		                    <BitsName>Service Identification</BitsName>
		                </Bits> 
		            </Fixed>
        	</DataItemFormat>
        	<DataItemNote>the service identification is allocated by the SDPS</DataItemNote>
    	</DataItem>
 
	<DataItem id="020">
		<DataItemName>Batch Number</DataItemName>
		<DataItemDefinition>A number indicating the completion of a service for that batch of track data, from 0 to N-1, N being the number of batches used to make one complete processing cycle.</DataItemDefinition>
		<DataItemFormat desc="One-Octet fixed length data item.">
			<Fixed length="1">
				<Bits from="8" to="1">
					<BitsShortName>BTN</BitsShortName>
					<BitsName>Batch Number</BitsName>
				</Bits>
			</Fixed>
		</DataItemFormat>
	</DataItem>		  
  
	<DataItem id="030">
		<DataItemName>Time Of Message</DataItemName>
		<DataItemDefinition>Absolute time stamping of the message in the form of elapsed time since last midnight.</DataItemDefinition>
		<DataItemFormat desc="Three-byte fixed length data item.">
			<Fixed length="3">
				<Bits from="24" to="1" encode="unsigned">
					<BitsShortName>ToD</BitsShortName>
					<BitsName>Time Of Message</BitsName>
					<BitsUnit scale="0.0078125">s</BitsUnit>
				</Bits>
			</Fixed>
		</DataItemFormat>
		<DataItemNote>The time of the day value is reset to zero at every midnight.</DataItemNote>
	</DataItem>		

	<DataItem id="040">
		<DataItemName>SDPS Configuration and Status</DataItemName>
		<DataItemDefinition>Status of an SDPS.</DataItemDefinition>
		<DataItemFormat desc="One-Octet fixed length data item.">
			<Fixed length="1">
				<Bits from="8" to="7">
					<BitsShortName>NOGO</BitsShortName>
					<BitsName>NOGO</BitsName>
					<BitsValue val="0">Operational</BitsValue>
                    			<BitsValue val="1">Degraded</BitsValue>
                    			<BitsValue val="2">Not currently connected</BitsValue>
								<BitsValue val="3">Unknown</BitsValue>
				</Bits>
				<Bits bit="6">
                    <BitsShortName>OVL</BitsShortName>
                    <BitsName>Overload</BitsName>
								<BitsValue val="0">Default</BitsValue>
                    			<BitsValue val="1">Overload</BitsValue>
                </Bits>
				<Bits bit="5">
                    <BitsShortName>TSV</BitsShortName>
                    <BitsName>Time Source Status</BitsName>
								<BitsValue val="0">Default</BitsValue>
                    			<BitsValue val="1">Invalid Time Source</BitsValue>
                </Bits>
				<Bits from="4" to="3">
					<BitsShortName>PSS</BitsShortName>
					<BitsName>Processing System Status</BitsName>
								<BitsValue val="0">Not applicable</BitsValue>
                    			<BitsValue val="1">SDPS-1 selected</BitsValue>
                    			<BitsValue val="2">SDPS-2 selected</BitsValue>
                    			<BitsValue val="3">SDPS-3 selected</BitsValue>
				</Bits>
                <Bits from="2" to="1">
					<BitsShortName>spare</BitsShortName>
                    			<BitsName>Spare bits se to 0</BitsName>
                    			<BitsConst>0</BitsConst>
				</Bits>
			</Fixed>
		</DataItemFormat>
	</DataItem>	
	
	<DataItem id="050">
        <DataItemName>Service Status Report</DataItemName>
        <DataItemDefinition>Report sent by the SDPS related to a service</DataItemDefinition>
        <DataItemFormat desc="One-byte fixed 1ength data item.">
            <Fixed length="1">
                <Bits from="8" to="1">
                    <BitsShortName>REPORT</BitsShortName>
                    <BitsName>Service Status Report</BitsName>
			                	<BitsValue val="1">service degradation</BitsValue>
			            		<BitsValue val="2">service degradation ended</BitsValue>
			       		        <BitsValue val="3">main radar out of service</BitsValue>
					 	<BitsValue val="4">service interrupted by the operator</BitsValue>
						<BitsValue val="5">service interrupted due to contingency</BitsValue>
						<BitsValue val="6">ready for service restart after contingency</BitsValue>
						<BitsValue val="7">service ended by the operator</BitsValue>
						<BitsValue val="8">failure of user main radar</BitsValue>
						<BitsValue val="9">service restarted by the operator</BitsValue>
						<BitsValue val="10">main radar becoming operational</BitsValue>
						<BitsValue val="11">main radar becoming degraded</BitsValue>
						<BitsValue val="12">service continuity interrupted due to disconnection with adjacent unit</BitsValue>
						<BitsValue val="13">service continuity restarted</BitsValue>
						<BitsValue val="14">service synchronised on backup radar</BitsValue>
						<BitsValue val="15">service synchronised on main radar</BitsValue>
						<BitsValue val="16">main and backup radar, if any, failed</BitsValue>					
                </Bits>
            </Fixed>
        </DataItemFormat>
    </DataItem>


    <UAP>
		<UAPItem bit="0" frn="1" len="2">010</UAPItem>
		<UAPItem bit="1" frn="2" len="1">000</UAPItem>
		<UAPItem bit="2" frn="3" len="1">015</UAPItem>
		<UAPItem bit="3" frn="4" len="3">030</UAPItem>
		<UAPItem bit="4" frn="5" len="1">020</UAPItem>
		<UAPItem bit="5" frn="6" len="1">040</UAPItem>
		<UAPItem bit="6" frn="7" len="1">050</UAPItem>
        <UAPItem bit="7" frn="FX" len="-">-</UAPItem>
        <UAPItem bit="8" frn="8" len="-">-</UAPItem>
        <UAPItem bit="9" frn="9" len="-">-</UAPItem>
        <UAPItem bit="10" frn="10" len="-">-</UAPItem>
		<UAPItem bit="11" frn="11" len="-">-</UAPItem>
		<UAPItem bit="12" frn="12" len="-">-</UAPItem>
		<UAPItem bit="13" frn="13" len="1+1+">RE</UAPItem>
		<UAPItem bit="14" frn="14" len="1+1+">SP</UAPItem>
        <UAPItem bit="15" frn="FX" len="-">-</UAPItem>
    </UAP>
        
</Category>
